Support multiple identity providers on the `okta_policy_rule_idp_discovery` resource
okta/terraform-provider-okta pull request #1214
Opened 2022-07-21 09:14 UTC by felixcolaci

Hi.
I noticed a shortcoming between the management ui and the `okta_policy_rule_idp_disvovery`. While it is possible to configure multiple identity providers for a given rule through the ui this is not possible through terraform yet.

### UI
![Bildschirmfoto 2022-07-21 um 10 47 48](https://user-images.githubusercontent.com/34742348/180176452-8fef6e0c-88fc-457a-bbad-f94cb32b705b.png)

### Terraform
```hcl
resource "okta_policy_rule_idp_discovery" "my_rule" {
  name      = "My Rule"
  policy_id = "some-policy-id"
  idp_id    = "some-idp-id"
  idp_type = "idp-type"
}

```
## Changes
I suggest to add the possibility to configure multiple idps per discovery rule and use it in terraform like this:
```hcl
resource "okta_policy_rule_idp_discovery" "my_rule" {
  name      = "My Rule"
  policy_id = "some-policy-id"

  idp {
    id   = okta_idp_social.google.id
    type = "GOOGLE"
  }
  idp {
    id   = okta_idp_social.facebook.id
    type = "FACEBOOK"
  }
}

```
I implemented this change in a backwards compatible way. If the legacy attributes `idp_id` and `idp_type` are set they will be used as before. However if the newly added `idp {}` list is used the list will take advantage over the legacy attributes.
Let me know what you think! 
Cheers, Felix

2022-07-21 18:55 UTC, monde commented
Thanks @felixcolaci , I'll review today/tomorrow.

2022-09-14 14:30 UTC, monde requested changes
@felixcolaci apologies for getting to this late. I'm about to do a big bug fix release as v3.36.0. I want to separate this PR as a separate release v3.36.0

2022-09-14 14:30 UTC, monde commented on website/docs/r/policy_rule_idp_discovery.html.markdown
> +````hcl
Code blocks need to be three ticks
```hcl
# words
```
You can double check how documentation renders here https://registry.terraform.io/tools/doc-preview

2022-09-14 14:30 UTC, monde commented on website/docs/r/policy_rule_idp_discovery.html.markdown
> +````
three ticks

2022-09-14 16:14 UTC, monde commented
The resource test is failing on the first step. I need to spend some time looking into this. I'm going to triage into our internal work backlog.

```
TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^TestAccOktaPolicyRuleIdpDiscovery_crud$ ./okta 2>&1
=== RUN   TestAccOktaPolicyRuleIdpDiscovery_crud
    resource_okta_policy_rule_idp_discovery_test.go:28: Step 1/6 error: Error running apply: exit status 1

        Error: failed to set authentication policy for an SAML application: failed delete authentication policy: the API returned an error: The request was not valid: Invalid policy type specified.

          with okta_app_saml.test,
          on terraform_plugin_test.tf line 40, in resource "okta_app_saml" "test":
          40: resource "okta_app_saml" "test" {

--- FAIL: TestAccOktaPolicyRuleIdpDiscovery_crud (4.38s)
FAIL
FAIL    github.com/okta/terraform-provider-okta/okta    4.641s
FAIL
```

2022-09-14 16:15 UTC, monde commented
Okta internal ref: https://oktainc.atlassian.net/browse/OKTA-532577

2022-10-24 19:13 UTC, monde commented
I'll try to dedicate time to look at this in my current sprint.

2023-08-07 00:12 UTC, closed without merging

2024-02-08 17:25 UTC, ben-contreras commented
is there any way to support this funcionality with the current code?

2024-10-29 15:35 UTC, HeroesFR commented
@monde is there any update on this feature ?