Add authentication policy to bookmark app
okta/terraform-provider-okta pull request #1366
Opened 2022-11-15 15:34 UTC by jakezarobsky-8451

closes #1352

2022-11-15 15:58 UTC, monde commented
Thanks @jakezarobsky-8451 we need integration tests on PRs. I try to help out with this when I can. My bandwidth is low right now, if you could take a try at it the test is in https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_bookmark_test.go . For new refinements I like to inline the config like the example [TestAccAppBookmarkApplication_timeouts](https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_app_bookmark_test.go#L55-L64)

2022-11-15 16:49 UTC, jakezarobsky-8451 commented
I'll try it out - was going to add a test but didn't see a good example for the authentication policy in the other apps - which is why I didn't include it originally.

2022-11-15 17:31 UTC, jakezarobsky-8451 commented
@monde  - I think I updates this - didn't end up inlining the configs - just to minimize the changes in the PR. If that is really necessary for merging I can do it - do you want me to do anything with the examples if I do make that change?

2022-11-15 18:20 UTC, monde commented
@jakezarobsky-8451 this looks good. Since this is net-new, that is good to add it in the examples files. You reminded me, when it's a bug being fixed I prefer to inline the configs in the ITs and not clutter up clean examples. This also shows the config next to test demonstrating the fix has occurred.

I'll run this locally later today and finish the review.

2022-11-17 16:52 UTC, jakezarobsky-8451 commented
@monde  - Sorry to be a thorn in the side - were you able to see if this would run locally?

2022-11-17 17:20 UTC, monde commented
🤔 you didn't actually run your tests:
```
for t in `grep "func Test" okta/resource_okta_app_bookmark_test.go | awk '{ print $2}'| sed -e 's/(.*//g'`; do
TF_LOG=warn TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^${t}$ ./okta
done
# github.com/okta/terraform-provider-okta/okta [github.com/okta/terraform-provider-okta/okta.test]
okta/resource_okta_app_bookmark.go:39:5: syntax error: unexpected newline in composite literal; possibly missing comma or }
FAIL    github.com/okta/terraform-provider-okta/okta [build failed]
FAIL
# github.com/okta/terraform-provider-okta/okta [github.com/okta/terraform-provider-okta/okta.test]
okta/resource_okta_app_bookmark.go:39:5: syntax error: unexpected newline in composite literal; possibly missing comma or }
FAIL    github.com/okta/terraform-provider-okta/okta [build failed]
FAIL
```

once you fix your code I need you to also run and make any recommended fixes
```
make vet
```

2022-11-17 17:21 UTC, monde requested changes

2022-11-17 17:21 UTC, monde commented on examples/okta_app_bookmark/basic.tf
> +  groups                 = [okta_group.group.id]
nit, lining up whitespace and equals

2022-11-17 17:21 UTC, monde commented on okta/resource_okta_app_bookmark.go
> +			}
```
okta/resource_okta_app_bookmark.go:39:5: syntax error: unexpected newline in composite literal; possibly missing comma or }
```

2022-11-17 18:00 UTC, jakezarobsky-8451 commented
That's definitely my bad - never written go before and thought I got the syntax down. I've installed the binary, run the formatter, corrected the tests. 

I'm thinking the ACC tests are still going to fail just because there's not a data reference to a specific authentication policy in the ACC test tenant - I didn't see authentication_policy on other tests

2022-11-17 18:14 UTC, monde commented
Thanks @jakezarobsky-8451 , I won't haze you anymore 😺 
I'll start a local branch, merge in your changes and fix the tests. Thanks for your contribution.

2022-11-17 19:04 UTC, jakezarobsky-8451 commented
Thank you Mike!

2022-11-17 20:21 UTC, merged