add support device assurance
okta/terraform-provider-okta pull request #1659
Opened 2023-08-01 21:44 UTC by duytiennguyen-okta

2023-08-02 18:45 UTC, lucascantor commented
@duytiennguyen-okta thank you so much for working on this. It sincerely means the world to me.

2023-08-04 21:21 UTC, duytiennguyen-okta commented
> @duytiennguyen-okta thank you so much for working on this. It sincerely means the world to me.

@lucascantor you mentioned in the issue that  ```okta_app_signon_policy_rule resources cannot [have Device Assurance policies added to them](https://help.okta.com/oie/en-us/Content/Topics/identity-engine/devices/device-assurance-policy-rule.htm) until an Okta Terraform provider version is released with support for this.```. What do you mean by that? Can you give me an example?

2023-08-04 21:34 UTC, monde requested changes

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_androi_test.go
> +func TestAccPolicyDeviceAssuranceAndroid(t *testing.T) {
TestAccResourceOktaPolicyDeviceAssuranceAndroid

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_chromeOS_test.go
> +func TestAccPolicyDeviceAssuranceChromeOS(t *testing.T) {
TestAccResourceOktaPolicyDeviceAssuranceChromeOS

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_iOS_test.go
> +func TestAccPolicyDeviceAssuranceIOS(t *testing.T) {
TestAccResourceOktaPolicyDeviceAssuranceIOS

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_macOS_test.go
> +func TestAccPolicyDeviceAssuranceMacOS(t *testing.T) {
TestAccResourceOktaPolicyDeviceAssuranceMacOS

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_window_test.go
> +func TestAccPolicyDeviceAssuranceWindows(t *testing.T) {
TestAccResourceOktaPolicyDeviceAssuranceWindows

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_androi_test.go
> +package okta
test file name has a typo ~~resource_okta_policy_device_assurance_androi_test.go~~ resource_okta_policy_device_assurance_android_test.go

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_androi.go
> +package okta
file name has a typo ~~resource_okta_policy_device_assurance_androi.go~~ resource_okta_policy_device_assurance_android.go

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_chromeOS.go
> +package okta
Golang guideline is lower case file names ~~chromeOS.go~~ chromeos.go

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_chromeOS_test.go
> +package okta
Golang guideline is lower case file names ~~chromeOS_test.go~~ chromeos_test.go

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_iOS.go
> +package okta
Golang guideline is lower case file names ~~iOS.go~~ ios.go

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_iOS_test.go
> +package okta
Golang guideline is lower case file names ~~iOS_test.go~~ ios_test.go

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_macOS.go
> +package okta
Golang guideline is lower case file names ~~macOS.go~~ macos.go

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_macOS_test.go
> +package okta
Golang guideline is lower case file names ~~macOS_test.go~~ macos_test.go

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_window.go
> +package okta
Probably should be plural ~~window.go~~ windows.go

2023-08-04 21:34 UTC, monde commented on okta/resource_okta_policy_device_assurance_window_test.go
> +package okta
Probably should be plural ~~window_test.go~~ windows_test.go

2023-08-05 03:17 UTC, lucascantor commented
@duytiennguyen-okta to answer your question, when I made that comment on https://github.com/okta/terraform-provider-okta/issues/1240 I just meant that we can't perform the [`Add device assurance to an authentication policy`](https://help.okta.com/oie/en-us/Content/Topics/identity-engine/devices/device-assurance-policy-rule.htm) task via Terraform.

2023-08-07 17:49 UTC, duytiennguyen-okta commented
@monde leave the file name be. I have issue with work space that require the file to be named that way, otherwise the workspace does not recognized the file

2023-08-08 16:02 UTC, monde approved these changes

2023-08-08 16:03 UTC, merged