New data sources
okta/terraform-provider-okta pull request #1816
Opened 2023-11-15 23:46 UTC by steveAG

Sorry for the multiple resource PR, I caught that in the contribution guidelines when creating the PR, I'll keep that in mind for future contributions, and I can cherry pick these into three PRs if you prefer.

Adds the following data sources:

- `okta_apps` closes #1528  
  - Includes doc and ACC tests for 0/1/2 results.
- `okta_custom_admin_role` closes #1523 
  - Includes doc and ACC test.
- `okta_group_rules`
  - Includes doc and ACC tests for 0/1/2 results.

2023-11-17 16:13 UTC, duytiennguyen-okta commented on okta/data_source_okta_apps.go
> +		_ = d.Set("apps", make([]map[string]interface{}, 0))
Should this error out when it cannot filter?

2023-11-17 16:38 UTC, steveAG commented on okta/data_source_okta_apps.go
> +		_ = d.Set("apps", make([]map[string]interface{}, 0))
When no match is found based on the filter?

I don't think so, data sources that return a single instance of a resource throw an error on no match, but this is consistent with the behavior of all of the existing multi-instance data sources I've seen in the provider.
ie [users](https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_users.go#L113), [groups](https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_groups.go#L91), & [group assignments](https://github.com/okta/terraform-provider-okta/blob/master/okta/data_source_okta_app_group_assignments.go#L55) all return an empty array if there are no matches.

2023-11-17 16:56 UTC, duytiennguyen-okta requested changes
I don't have the issue with the purpose of the PR itself, however as we are trying to move away from plugin sdk to framework sdk, can you please port it over to framework sdk? Here is an example of another contributor who has done it #1726 . Thank you for your effort

2023-11-28 22:24 UTC, monde commented
@steveAG I'm going to help here and bring your original work into a PR that I can refactor to use the TF Plugin Framework. Do you have Okta Individual Contributor License Agreement on file with us https://developer.okta.com/cla/ ?

2023-11-28 22:38 UTC, monde commented
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-671288

2023-11-29 00:02 UTC, steveAG commented
Thanks a million @monde!

I've been inundated with work and haven't gotten to digging into moving to the framework SDK yet.

Yes I have an agreement on file, signed and sent in June 2023.

2025-01-17 21:41 UTC, steveAG commented
Closing stale PR, this was addressed in #2136

2025-01-17 21:41 UTC, closed without merging